version: "3"

services:
    backend:
      container_name: dc-postcode-backend
      build:
        context: .
      command: ["uwsgi", "--socket", "0.0.0.0:8080", "--workers", "10", "--protocol=http", "-w", "wsgi"]
      ports:
        - "8080"
      volumes:
        - .:/deploy
      working_dir: /deploy
      networks:
        - nginx-network

    nginx:
      container_name: dc-postcode-nginx
      image: nginx:1.13.9
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
      links:
        - backend:backend
      ports:
        - "80:80"
      command: ["nginx", "-g", "daemon off;"]
      networks:
        - nginx-network

networks:
    nginx-network:
      driver: bridge
